import type {
  Equipment,
  RecoveryEvent,
  ESGMetrics,
  FleetBreakdown,
  RegionalCompliance,
  TemperatureData,
  Alert,
  AuthorizedCenter,
} from "./types";

// ─── Equipment Records ────────────────────────────────────────────────────────
export const equipment: Equipment[] = [
  {
    id: "EQ-001",
    model: "Torino LT-650",
    brand: "Imbera",
    location: "OXXO Insurgentes Sur #3421",
    city: "Ciudad de México",
    state: "CDMX",
    installationDate: "2012-03-15",
    gasType: "R-404A",
    gasCharge: 1.8,
    lastServiceDate: "2023-11-20",
    technician: "Carlos Mendoza Reyes",
    coordinates: { lat: 19.3835, lng: -99.1652 },
    status: "critical",
    age: 13,
    integrityPercent: 22,
    remainingLifePercent: 18,
  },
  {
    id: "EQ-002",
    model: "Vision 580",
    brand: "Arca Continental",
    location: "OXXO Reforma #1205",
    city: "Monterrey",
    state: "Nuevo León",
    installationDate: "2018-07-22",
    gasType: "R-134a",
    gasCharge: 2.1,
    lastServiceDate: "2024-08-15",
    technician: "Alejandro Torres Vega",
    coordinates: { lat: 25.6714, lng: -100.309 },
    status: "active",
    age: 7,
    integrityPercent: 87,
    remainingLifePercent: 74,
  },
  {
    id: "EQ-003",
    model: "Eco-Cool 320",
    brand: "Mabe",
    location: "Supermercado La Comer, Pedregal",
    city: "Ciudad de México",
    state: "CDMX",
    installationDate: "2020-01-10",
    gasType: "R-290",
    gasCharge: 0.15,
    lastServiceDate: "2024-10-05",
    technician: "Roberto Sánchez Lima",
    coordinates: { lat: 19.3238, lng: -99.204 },
    status: "active",
    age: 5,
    integrityPercent: 94,
    remainingLifePercent: 88,
  },
  {
    id: "EQ-004",
    model: "Polar Max 720",
    brand: "Torrey",
    location: "Walmart Supercenter Tlaquepaque",
    city: "Guadalajara",
    state: "Jalisco",
    installationDate: "2013-09-30",
    gasType: "R-404A",
    gasCharge: 2.4,
    lastServiceDate: "2023-06-12",
    technician: "Héctor Ramírez Cruz",
    coordinates: { lat: 20.6597, lng: -103.3496 },
    status: "critical",
    age: 12,
    integrityPercent: 31,
    remainingLifePercent: 22,
  },
  {
    id: "EQ-005",
    model: "FreshPro 450",
    brand: "Imbera",
    location: "OXXO Calle 5 de Mayo #88",
    city: "Puebla",
    state: "Puebla",
    installationDate: "2019-05-18",
    gasType: "R-134a",
    gasCharge: 1.9,
    lastServiceDate: "2024-09-22",
    technician: "Luis Felipe Morales",
    coordinates: { lat: 19.0435, lng: -98.1976 },
    status: "active",
    age: 6,
    integrityPercent: 81,
    remainingLifePercent: 68,
  },
  {
    id: "EQ-006",
    model: "Green Series G-180",
    brand: "Mabe",
    location: "Soriana Oriente",
    city: "Tijuana",
    state: "Baja California",
    installationDate: "2021-11-03",
    gasType: "R-600a",
    gasCharge: 0.09,
    lastServiceDate: "2024-11-10",
    technician: "Marco Antonio Díaz",
    coordinates: { lat: 32.5149, lng: -117.0382 },
    status: "active",
    age: 4,
    integrityPercent: 97,
    remainingLifePercent: 92,
  },
  {
    id: "EQ-007",
    model: "Torino LT-650",
    brand: "Imbera",
    location: "OXXO Blvd. Colosio #1100",
    city: "Hermosillo",
    state: "Sonora",
    installationDate: "2014-06-20",
    gasType: "R-404A",
    gasCharge: 1.8,
    lastServiceDate: "2023-04-18",
    technician: "José Luis Acosta",
    coordinates: { lat: 29.0729, lng: -110.9559 },
    status: "warning",
    age: 11,
    integrityPercent: 48,
    remainingLifePercent: 35,
  },
  {
    id: "EQ-008",
    model: "Eco Breeze 400",
    brand: "Torrey",
    location: "H-E-B Cumbres",
    city: "Monterrey",
    state: "Nuevo León",
    installationDate: "2017-02-14",
    gasType: "R-134a",
    gasCharge: 2.3,
    lastServiceDate: "2024-07-30",
    technician: "Alejandro Torres Vega",
    coordinates: { lat: 25.7647, lng: -100.3337 },
    status: "warning",
    age: 8,
    integrityPercent: 55,
    remainingLifePercent: 42,
  },
  {
    id: "EQ-009",
    model: "Vision 580",
    brand: "Arca Continental",
    location: "OXXO Prolongación Corregidora",
    city: "Querétaro",
    state: "Querétaro",
    installationDate: "2022-03-07",
    gasType: "R-134a",
    gasCharge: 2.1,
    lastServiceDate: "2024-12-01",
    technician: "Sandra Viveros Peña",
    coordinates: { lat: 20.5888, lng: -100.3899 },
    status: "active",
    age: 3,
    integrityPercent: 98,
    remainingLifePercent: 95,
  },
  {
    id: "EQ-010",
    model: "Polar Max 720",
    brand: "Torrey",
    location: "Chedraui Villahermosa Centro",
    city: "Villahermosa",
    state: "Tabasco",
    installationDate: "2011-08-25",
    gasType: "R-404A",
    gasCharge: 2.5,
    lastServiceDate: "2022-12-10",
    technician: "Miguel Ángel Fuentes",
    coordinates: { lat: 17.9897, lng: -92.9476 },
    status: "critical",
    age: 14,
    integrityPercent: 14,
    remainingLifePercent: 10,
  },
  {
    id: "EQ-011",
    model: "FreshPro 450",
    brand: "Imbera",
    location: "Walmart Las Américas",
    city: "Mérida",
    state: "Yucatán",
    installationDate: "2016-04-12",
    gasType: "R-134a",
    gasCharge: 1.9,
    lastServiceDate: "2024-03-14",
    technician: "Fernanda Castillo Ruíz",
    coordinates: { lat: 20.9674, lng: -89.5926 },
    status: "warning",
    age: 9,
    integrityPercent: 52,
    remainingLifePercent: 39,
  },
  {
    id: "EQ-012",
    model: "Green Series G-180",
    brand: "Mabe",
    location: "OXXO Av. Universidad #2870",
    city: "San Luis Potosí",
    state: "San Luis Potosí",
    installationDate: "2023-01-19",
    gasType: "R-600a",
    gasCharge: 0.09,
    lastServiceDate: "2024-10-28",
    technician: "Rodrigo Esparza Nava",
    coordinates: { lat: 22.1565, lng: -100.9855 },
    status: "active",
    age: 2,
    integrityPercent: 99,
    remainingLifePercent: 97,
  },
  {
    id: "EQ-013",
    model: "Eco-Cool 320",
    brand: "Mabe",
    location: "Costco Juriquilla",
    city: "Querétaro",
    state: "Querétaro",
    installationDate: "2021-06-30",
    gasType: "R-290",
    gasCharge: 0.15,
    lastServiceDate: "2024-11-15",
    technician: "Sandra Viveros Peña",
    coordinates: { lat: 20.7056, lng: -100.4503 },
    status: "active",
    age: 4,
    integrityPercent: 91,
    remainingLifePercent: 85,
  },
  {
    id: "EQ-014",
    model: "Torino LT-650",
    brand: "Imbera",
    location: "OXXO Av. López Mateos #5430",
    city: "León",
    state: "Guanajuato",
    installationDate: "2015-11-08",
    gasType: "R-404A",
    gasCharge: 1.8,
    lastServiceDate: "2023-09-06",
    technician: "Eduardo Gutiérrez Leal",
    coordinates: { lat: 21.1236, lng: -101.6823 },
    status: "warning",
    age: 10,
    integrityPercent: 43,
    remainingLifePercent: 30,
  },
  {
    id: "EQ-015",
    model: "Vision 580",
    brand: "Arca Continental",
    location: "OXXO Revolución #890",
    city: "Chihuahua",
    state: "Chihuahua",
    installationDate: "2020-08-14",
    gasType: "R-134a",
    gasCharge: 2.1,
    lastServiceDate: "2024-06-20",
    technician: "Patricia Ramos Soto",
    coordinates: { lat: 28.6353, lng: -106.0889 },
    status: "active",
    age: 5,
    integrityPercent: 83,
    remainingLifePercent: 71,
  },
  {
    id: "EQ-016",
    model: "Eco Breeze 400",
    brand: "Torrey",
    location: "Sam's Club Saltillo",
    city: "Saltillo",
    state: "Coahuila",
    installationDate: "2019-12-03",
    gasType: "R-134a",
    gasCharge: 2.3,
    lastServiceDate: "2024-08-09",
    technician: "Jorge Ibarra Montoya",
    coordinates: { lat: 25.4232, lng: -101.0033 },
    status: "active",
    age: 6,
    integrityPercent: 76,
    remainingLifePercent: 63,
  },
  {
    id: "EQ-017",
    model: "Polar Max 720",
    brand: "Torrey",
    location: "Plaza Sendero Culiacán",
    city: "Culiacán",
    state: "Sinaloa",
    installationDate: "2013-04-17",
    gasType: "R-404A",
    gasCharge: 2.4,
    lastServiceDate: "2023-02-28",
    technician: "Armando Leyva Castro",
    coordinates: { lat: 24.7994, lng: -107.3878 },
    status: "critical",
    age: 12,
    integrityPercent: 27,
    remainingLifePercent: 15,
  },
  {
    id: "EQ-018",
    model: "Green Series G-180",
    brand: "Mabe",
    location: "Soriana Hipermart Xalapa",
    city: "Xalapa",
    state: "Veracruz",
    installationDate: "2022-09-25",
    gasType: "R-600a",
    gasCharge: 0.09,
    lastServiceDate: "2024-09-14",
    technician: "Diana Montiel Espinoza",
    coordinates: { lat: 19.5438, lng: -96.9102 },
    status: "active",
    age: 3,
    integrityPercent: 96,
    remainingLifePercent: 91,
  },
  {
    id: "EQ-019",
    model: "Eco-Cool 320",
    brand: "Mabe",
    location: "OXXO Av. Colón #245",
    city: "Aguascalientes",
    state: "Aguascalientes",
    installationDate: "2021-03-11",
    gasType: "R-290",
    gasCharge: 0.15,
    lastServiceDate: "2024-12-05",
    technician: "Iván Pérez Herrera",
    coordinates: { lat: 21.8799, lng: -102.2914 },
    status: "active",
    age: 4,
    integrityPercent: 92,
    remainingLifePercent: 87,
  },
  {
    id: "EQ-020",
    model: "FreshPro 450",
    brand: "Imbera",
    location: "La Europea Polanco",
    city: "Ciudad de México",
    state: "CDMX",
    installationDate: "2016-07-06",
    gasType: "R-134a",
    gasCharge: 1.9,
    lastServiceDate: "2024-05-18",
    technician: "Carlos Mendoza Reyes",
    coordinates: { lat: 19.4326, lng: -99.1958 },
    status: "warning",
    age: 9,
    integrityPercent: 57,
    remainingLifePercent: 44,
  },
];

// ─── Recovery Events ──────────────────────────────────────────────────────────
export const recoveryEvents: RecoveryEvent[] = [
  {
    id: "REC-2401",
    technicianName: "Carlos Mendoza Reyes",
    certificationNumber: "CERT-NOM-001234",
    equipmentId: "EQ-001",
    gasRecoveredKg: 1.72,
    destinationCenter: "Centro Certificado Norte — Monterrey",
    date: "2024-11-28",
    semarnatManifest: "SEMA-2024-MX-88741",
    retcNumber: "RETC-2024-001-MX",
    gasCondition: "destroy",
  },
  {
    id: "REC-2402",
    technicianName: "Alejandro Torres Vega",
    certificationNumber: "CERT-NOM-002891",
    equipmentId: "EQ-008",
    gasRecoveredKg: 2.15,
    destinationCenter: "Centro Certificado Noreste — Saltillo",
    date: "2024-12-02",
    semarnatManifest: "SEMA-2024-MX-88802",
    retcNumber: "RETC-2024-002-NL",
    gasCondition: "treatment",
  },
  {
    id: "REC-2403",
    technicianName: "Héctor Ramírez Cruz",
    certificationNumber: "CERT-NOM-003512",
    equipmentId: "EQ-004",
    gasRecoveredKg: 2.38,
    destinationCenter: "Centro Certificado Occidente — Guadalajara",
    date: "2024-12-05",
    semarnatManifest: "SEMA-2024-MX-88965",
    retcNumber: "RETC-2024-003-JA",
    gasCondition: "destroy",
  },
  {
    id: "REC-2404",
    technicianName: "Sandra Viveros Peña",
    certificationNumber: "CERT-NOM-004178",
    equipmentId: "EQ-013",
    gasRecoveredKg: 0.14,
    destinationCenter: "Centro Certificado Centro — Querétaro",
    date: "2024-12-08",
    semarnatManifest: "SEMA-2024-MX-89101",
    retcNumber: "RETC-2024-004-QR",
    gasCondition: "reusable",
  },
  {
    id: "REC-2405",
    technicianName: "Miguel Ángel Fuentes",
    certificationNumber: "CERT-NOM-005044",
    equipmentId: "EQ-010",
    gasRecoveredKg: 2.44,
    destinationCenter: "Centro Certificado Sureste — Mérida",
    date: "2024-12-10",
    semarnatManifest: "SEMA-2024-MX-89234",
    retcNumber: "RETC-2024-005-TA",
    gasCondition: "destroy",
  },
  {
    id: "REC-2406",
    technicianName: "Patricia Ramos Soto",
    certificationNumber: "CERT-NOM-006321",
    equipmentId: "EQ-015",
    gasRecoveredKg: 1.98,
    destinationCenter: "Centro Certificado Norte — Chihuahua",
    date: "2024-12-12",
    semarnatManifest: "SEMA-2024-MX-89310",
    retcNumber: "RETC-2024-006-CH",
    gasCondition: "reusable",
  },
  {
    id: "REC-2407",
    technicianName: "Armando Leyva Castro",
    certificationNumber: "CERT-NOM-007890",
    equipmentId: "EQ-017",
    gasRecoveredKg: 2.31,
    destinationCenter: "Centro Certificado Pacífico — Culiacán",
    date: "2024-12-14",
    semarnatManifest: "SEMA-2024-MX-89451",
    retcNumber: "RETC-2024-007-SI",
    gasCondition: "destroy",
  },
  {
    id: "REC-2408",
    technicianName: "Diana Montiel Espinoza",
    certificationNumber: "CERT-NOM-008654",
    equipmentId: "EQ-018",
    gasRecoveredKg: 0.089,
    destinationCenter: "Centro Certificado Golfo — Veracruz",
    date: "2024-12-16",
    semarnatManifest: "SEMA-2024-MX-89567",
    retcNumber: "RETC-2024-008-VE",
    gasCondition: "reusable",
  },
  {
    id: "REC-2409",
    technicianName: "Eduardo Gutiérrez Leal",
    certificationNumber: "CERT-NOM-009231",
    equipmentId: "EQ-014",
    gasRecoveredKg: 1.76,
    destinationCenter: "Centro Certificado Bajío — León",
    date: "2024-12-18",
    semarnatManifest: "SEMA-2024-MX-89690",
    retcNumber: "RETC-2024-009-GU",
    gasCondition: "treatment",
  },
  {
    id: "REC-2410",
    technicianName: "Carlos Mendoza Reyes",
    certificationNumber: "CERT-NOM-001234",
    equipmentId: "EQ-020",
    gasRecoveredKg: 1.85,
    destinationCenter: "Centro Certificado Centro — CDMX",
    date: "2024-12-20",
    semarnatManifest: "SEMA-2024-MX-89812",
    retcNumber: "RETC-2024-010-MX",
    gasCondition: "treatment",
  },
];

// ─── ESG Metrics ──────────────────────────────────────────────────────────────
export const esgMetrics: ESGMetrics = {
  totalEquipment: 847392,
  totalHFCInField: 254217,
  co2eAvoided: 38492,
  carbonCreditsGenerated: 40683,
  creditValueUSD: 2034150,
  hfcRecoveredTotal: 28450,
  monthlyRecovery: [
    { month: "Ene", kg: 1820 },
    { month: "Feb", kg: 2140 },
    { month: "Mar", kg: 2560 },
    { month: "Abr", kg: 2310 },
    { month: "May", kg: 2780 },
    { month: "Jun", kg: 3100 },
    { month: "Jul", kg: 2950 },
    { month: "Ago", kg: 2620 },
    { month: "Sep", kg: 2390 },
    { month: "Oct", kg: 2840 },
    { month: "Nov", kg: 2710 },
    { month: "Dic", kg: 3230 },
  ],
};

// ─── Fleet Breakdown ──────────────────────────────────────────────────────────
export const fleetBreakdown: FleetBreakdown[] = [
  { gasType: "R-134a", percentage: 61, equipmentCount: 516809 },
  { gasType: "R-404A", percentage: 28, equipmentCount: 237270 },
  { gasType: "R-290", percentage: 8, equipmentCount: 67791 },
  { gasType: "R-600a", percentage: 3, equipmentCount: 25422 },
];

// ─── Regional Compliance ──────────────────────────────────────────────────────
export const regionalCompliance: RegionalCompliance[] = [
  {
    region: "Centro (CDMX / Edomex)",
    equipmentCount: 198450,
    gasInField: 62100,
    equipmentRetired: 842,
    gasRecovered: 8210,
    creditsGenerated: 9031,
    status: "active",
    nomCompliance: "Cumple",
  },
  {
    region: "Noreste (NL / Coahuila)",
    equipmentCount: 134720,
    gasInField: 43890,
    equipmentRetired: 612,
    gasRecovered: 6140,
    creditsGenerated: 6754,
    status: "active",
    nomCompliance: "Cumple",
  },
  {
    region: "Occidente (Jalisco / Colima)",
    equipmentCount: 121830,
    gasInField: 38200,
    equipmentRetired: 490,
    gasRecovered: 4980,
    creditsGenerated: 5478,
    status: "warning",
    nomCompliance: "En proceso",
  },
  {
    region: "Norte (Chih / Son / Sin)",
    equipmentCount: 108640,
    gasInField: 35100,
    equipmentRetired: 380,
    gasRecovered: 3920,
    creditsGenerated: 4312,
    status: "warning",
    nomCompliance: "En proceso",
  },
  {
    region: "Sureste (Yuc / Tab / Cam)",
    equipmentCount: 143910,
    gasInField: 45600,
    equipmentRetired: 710,
    gasRecovered: 4120,
    creditsGenerated: 4532,
    status: "active",
    nomCompliance: "Cumple",
  },
  {
    region: "Bajío (Gto / Qro / Ags)",
    equipmentCount: 139842,
    gasInField: 29327,
    equipmentRetired: 186,
    gasRecovered: 1080,
    creditsGenerated: 1188,
    status: "critical",
    nomCompliance: "Incumple",
  },
];

// ─── Temperature History (for equipment detail) ───────────────────────────────
export const temperatureHistory: TemperatureData[] = [
  { month: "Ene", temp: -18.2 },
  { month: "Feb", temp: -17.8 },
  { month: "Mar", temp: -18.5 },
  { month: "Abr", temp: -17.1 },
  { month: "May", temp: -16.4 },
  { month: "Jun", temp: -15.9 },
  { month: "Jul", temp: -16.8 },
  { month: "Ago", temp: -17.3 },
  { month: "Sep", temp: -18.0 },
  { month: "Oct", temp: -18.4 },
  { month: "Nov", temp: -17.9 },
  { month: "Dic", temp: -18.6 },
];

// ─── Alert History ─────────────────────────────────────────────────────────
export const alertHistory: Alert[] = [
  {
    id: "ALT-001",
    timestamp: "2024-12-18 09:32",
    type: "critical",
    description: "Presión de gas por debajo del umbral mínimo (1.2 bar).",
  },
  {
    id: "ALT-002",
    timestamp: "2024-11-05 14:15",
    type: "warning",
    description: "Temperatura interna elevada: -14.1°C (umbral: -16°C).",
  },
  {
    id: "ALT-003",
    timestamp: "2024-09-22 11:48",
    type: "warning",
    description: "Compresor con 23% sobre la carga nominal recomendada.",
  },
];

// ─── Authorized Centers ───────────────────────────────────────────────────────
export const authorizedCenters: AuthorizedCenter[] = [
  { id: "AC-01", name: "Centro Certificado Centro — CDMX", city: "Ciudad de México", state: "CDMX" },
  { id: "AC-02", name: "Centro Certificado Norte — Monterrey", city: "Monterrey", state: "Nuevo León" },
  { id: "AC-03", name: "Centro Certificado Norte — Chihuahua", city: "Chihuahua", state: "Chihuahua" },
  { id: "AC-04", name: "Centro Certificado Noreste — Saltillo", city: "Saltillo", state: "Coahuila" },
  { id: "AC-05", name: "Centro Certificado Occidente — Guadalajara", city: "Guadalajara", state: "Jalisco" },
  { id: "AC-06", name: "Centro Certificado Bajío — León", city: "León", state: "Guanajuato" },
  { id: "AC-07", name: "Centro Certificado Pacífico — Culiacán", city: "Culiacán", state: "Sinaloa" },
  { id: "AC-08", name: "Centro Certificado Golfo — Veracruz", city: "Veracruz", state: "Veracruz" },
  { id: "AC-09", name: "Centro Certificado Sureste — Mérida", city: "Mérida", state: "Yucatán" },
];

// ─── Fleet Status Distribution (for donut chart) ─────────────────────────────
export const fleetStatusDistribution = [
  { name: "Activos", value: 78, color: "var(--accent-primary)" },
  { name: "Próx. fin de vida", value: 15, color: "var(--accent-warning)" },
  { name: "Críticos", value: 7, color: "var(--accent-danger)" },
];

// ─── Gas Type Pie Data ────────────────────────────────────────────────────────
export const gasTypePieData = [
  { name: "R-134a", value: 61, color: "var(--accent-warning)" },
  { name: "R-404A", value: 28, color: "var(--accent-danger)" },
  { name: "R-290", value: 8, color: "var(--accent-secondary)" },
  { name: "R-600a", value: 3, color: "var(--accent-primary)" },
];
